import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import {cn} from "@/lib/utils";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const baseFont = localfont({
  src:"../public/fonts/light.ttf"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(baseFont.className, "bg-[#53362D]")}>{children}</body>
    </html>
  );
}


